spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/maa?currentSchema=public
    # db-instance specific
    username: postgres
    password: root
    hikari:      connection-timeout: 40000
      minimum-idle: 5
      maximum-pool-size: 8
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: false
server:  port: 9090
